/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Luciano Acosta
 */
public class vistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaMenu() {
        initComponents();
        System.out.println("init components");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNvoProducto = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jlProductos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlVentas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlClientes = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnModProducto = new javax.swing.JButton();
        btnListarProd = new javax.swing.JButton();
        btnNvoCliente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlEmpleado = new javax.swing.JLabel();
        jlPunto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(31, 192, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 2));

        btnNvoProducto.setBackground(new java.awt.Color(0, 0, 0));
        btnNvoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNvoProducto.setText("Nuevo Producto");
        btnNvoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNvoProductoMousePressed(evt);
            }
        });
        btnNvoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNvoProductoActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(0, 0, 0));
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        jlProductos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moda.png"))); // NOI18N
        jlProductos.setText(" Productos");

        jlVentas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas (1).png"))); // NOI18N
        jlVentas.setText(" Ventas");

        jlClientes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jlClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jlClientes.setText(" Clientes");

        btnClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
        });

        btnModProducto.setBackground(new java.awt.Color(0, 0, 0));
        btnModProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnModProducto.setText("Modificar Producto");
        btnModProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModProductoMousePressed(evt);
            }
        });
        btnModProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProductoActionPerformed(evt);
            }
        });

        btnListarProd.setBackground(new java.awt.Color(0, 0, 0));
        btnListarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnListarProd.setText("Listar Productos");
        btnListarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarProdMousePressed(evt);
            }
        });
        btnListarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdActionPerformed(evt);
            }
        });

        btnNvoCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnNvoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNvoCliente.setText("Nuevo Cliente");
        btnNvoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNvoClienteMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(31, 192, 132));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Cerrar Sesión");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setPreferredSize(new java.awt.Dimension(140, 32));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jlClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jlVentas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jlProductos)))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNvoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(btnModProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNvoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentas)
                .addGap(104, 104, 104)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNvoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModProducto)
                .addGap(11, 11, 11)
                .addComponent(btnListarProd)
                .addGap(31, 31, 31)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNvoCliente)
                .addGap(11, 11, 11)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 192, 132));
        jLabel1.setText("EMPLEADO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 192, 132));
        jLabel6.setText("FECHA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 192, 132));
        jLabel7.setText("PUNTO DE VENTA:");

        jlFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlFecha.setForeground(new java.awt.Color(31, 192, 132));
        jlFecha.setText(" ");

        jlEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEmpleado.setForeground(new java.awt.Color(31, 192, 132));
        jlEmpleado.setText(" ");

        jlPunto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlPunto.setForeground(new java.awt.Color(31, 192, 132));
        jlPunto.setText("25");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlPunto))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(31, 192, 132));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 100));

        jlLogo.setBackground(new java.awt.Color(31, 192, 132));
        jlLogo.setFont(new java.awt.Font("Tahoma", 0, 39)); // NOI18N
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/percha (3).png"))); // NOI18N
        jlLogo.setText("TIENDA");

        jPanel4.setBackground(new java.awt.Color(31, 192, 132));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlLogo1.setBackground(new java.awt.Color(31, 192, 132));
        jlLogo1.setFont(new java.awt.Font("Tahoma", 0, 39)); // NOI18N
        jlLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/percha (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jlLogo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jlLogo)
                    .addContainerGap(24, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlLogo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jlLogo)
                    .addContainerGap(18, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNvoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvoClienteMousePressed
        btnVentas.setBackground(Color.black);
        btnVentas.setForeground(Color.white);
        btnNvoProducto.setBackground(Color.black);
        btnNvoProducto.setForeground(Color.white);
        btnClientes.setBackground(Color.black);
        btnClientes.setForeground(Color.white);
        btnNvoCliente.setBackground(Color.white);
        btnNvoCliente.setForeground(Color.black);
        btnListarProd.setBackground(Color.black);
        btnListarProd.setForeground(Color.white);
        btnModProducto.setBackground(Color.black);
        btnModProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnNvoClienteMousePressed

    private void btnListarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarProdActionPerformed

    private void btnListarProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProdMousePressed
        btnVentas.setBackground(Color.black);
        btnVentas.setForeground(Color.white);
        btnNvoProducto.setBackground(Color.black);
        btnNvoProducto.setForeground(Color.white);
        btnClientes.setBackground(Color.black);
        btnClientes.setForeground(Color.white);
        btnNvoCliente.setBackground(Color.black);
        btnNvoCliente.setForeground(Color.white);
        btnListarProd.setBackground(Color.white);
        btnListarProd.setForeground(Color.black);
        btnModProducto.setBackground(Color.black);
        btnModProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnListarProdMousePressed

    private void btnModProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModProductoActionPerformed

    private void btnModProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModProductoMousePressed
        btnVentas.setBackground(Color.black);
        btnVentas.setForeground(Color.white);
        btnNvoProducto.setBackground(Color.black);
        btnNvoProducto.setForeground(Color.white);
        btnClientes.setBackground(Color.black);
        btnClientes.setForeground(Color.white);
        btnNvoCliente.setBackground(Color.black);
        btnNvoCliente.setForeground(Color.white);
        btnListarProd.setBackground(Color.black);
        btnListarProd.setForeground(Color.white);
        btnModProducto.setBackground(Color.white);
        btnModProducto.setForeground(Color.black);
    }//GEN-LAST:event_btnModProductoMousePressed

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        btnVentas.setBackground(Color.black);
        btnVentas.setForeground(Color.white);
        btnNvoProducto.setBackground(Color.black);
        btnNvoProducto.setForeground(Color.white);
        btnClientes.setBackground(Color.white);
        btnClientes.setForeground(Color.black);
        btnNvoCliente.setBackground(Color.black);
        btnNvoCliente.setForeground(Color.white);
        btnListarProd.setBackground(Color.black);
        btnListarProd.setForeground(Color.white);
        btnModProducto.setBackground(Color.black);
        btnModProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnClientesMousePressed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed

    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        btnVentas.setBackground(Color.white);
        btnVentas.setForeground(Color.black);
        btnNvoProducto.setBackground(Color.black);
        btnNvoProducto.setForeground(Color.white);
        btnClientes.setBackground(Color.black);
        btnClientes.setForeground(Color.white);
        btnNvoCliente.setBackground(Color.black);
        btnNvoCliente.setForeground(Color.white);
        btnListarProd.setBackground(Color.black);
        btnListarProd.setForeground(Color.white);
        btnModProducto.setBackground(Color.black);
        btnModProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnVentasMousePressed

    private void btnNvoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNvoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvoProductoActionPerformed

    private void btnNvoProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNvoProductoMousePressed
        btnVentas.setBackground(Color.black);
        btnVentas.setForeground(Color.white);
        btnNvoProducto.setBackground(Color.white);
        btnNvoProducto.setForeground(Color.black);
        btnClientes.setBackground(Color.black);
        btnClientes.setForeground(Color.white);
        btnNvoCliente.setBackground(Color.black);
        btnNvoCliente.setForeground(Color.white);
        btnListarProd.setBackground(Color.black);
        btnListarProd.setForeground(Color.white);
        btnModProducto.setBackground(Color.black);
        btnModProducto.setForeground(Color.white);
    }//GEN-LAST:event_btnNvoProductoMousePressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnListarProd;
    public javax.swing.JButton btnModProducto;
    public javax.swing.JButton btnNvoCliente;
    public javax.swing.JButton btnNvoProducto;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel jlClientes;
    public javax.swing.JLabel jlEmpleado;
    public javax.swing.JLabel jlFecha;
    public javax.swing.JLabel jlLogo;
    public javax.swing.JLabel jlLogo1;
    public javax.swing.JLabel jlProductos;
    public javax.swing.JLabel jlPunto;
    public javax.swing.JLabel jlVentas;
    // End of variables declaration//GEN-END:variables
}
